// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import UploadContainerController from "./upload_container_controller"
application.register("upload-container", UploadContainerController)

import UploadElementController from "./upload_element"
application.register("upload-element", UploadElementController)
